/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * this is the admin homepage where the admin can see the stats on students enrolled,males,females,Programs
 * 
 */
public class adminHomePage extends javax.swing.JFrame {

    /**
     * Creates new form adminHomePage
     */
    ArrayList<String> adminInfo = new ArrayList<String>();

    DataBase db = new DataBase();
    ImageIntializer ig = new ImageIntializer();

    public adminHomePage() {
        initComponents();
    }

    public adminHomePage(String usr, String psswrd) {
        initComponents();
        adminInfo.add(usr);
        adminInfo.add(psswrd);
        loadAssets();
        this.setResizable(false);
        this.setTitle("Admin Page");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminNameLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        dashboardLbl = new javax.swing.JLabel();
        bussinessStudentLbl = new javax.swing.JLabel();
        archiveLbl = new javax.swing.JLabel();
        MaleLbl = new javax.swing.JLabel();
        enrolledLbl = new javax.swing.JLabel();
        femaleLbl = new javax.swing.JLabel();
        csStudentsLbl = new javax.swing.JLabel();
        bioStudentLbl = new javax.swing.JLabel();
        statsBackgroundLBl = new javax.swing.JLabel();
        seeAllLbl = new javax.swing.JLabel();
        refreshLbl = new javax.swing.JLabel();
        exitLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminNameLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminNameLbl.setText("d");
        getContentPane().add(adminNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ADMIN:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 60, 30));

        imgLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        getContentPane().add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 234, 220));

        dashboardLbl.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        dashboardLbl.setText("Dashboard");
        getContentPane().add(dashboardLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 260, 260));

        bussinessStudentLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        bussinessStudentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bussinessStudentLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bussinessStudentLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bussinessStudentLblMouseExited(evt);
            }
        });
        getContentPane().add(bussinessStudentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 180, 70));

        archiveLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        archiveLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archiveLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                archiveLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                archiveLblMouseExited(evt);
            }
        });
        getContentPane().add(archiveLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 180, 70));

        MaleLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        MaleLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaleLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaleLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaleLblMouseExited(evt);
            }
        });
        getContentPane().add(MaleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 70));

        enrolledLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        enrolledLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enrolledLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enrolledLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enrolledLblMouseExited(evt);
            }
        });
        getContentPane().add(enrolledLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 70));

        femaleLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        femaleLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femaleLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                femaleLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                femaleLblMouseExited(evt);
            }
        });
        getContentPane().add(femaleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 70));

        csStudentsLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        csStudentsLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                csStudentsLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                csStudentsLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                csStudentsLblMouseExited(evt);
            }
        });
        getContentPane().add(csStudentsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 70));

        bioStudentLbl.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        bioStudentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bioStudentLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bioStudentLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bioStudentLblMouseExited(evt);
            }
        });
        getContentPane().add(bioStudentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 180, 70));
        getContentPane().add(statsBackgroundLBl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 700));

        seeAllLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeAllLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seeAllLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seeAllLblMouseExited(evt);
            }
        });
        getContentPane().add(seeAllLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 80, 70));

        refreshLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshLblMouseExited(evt);
            }
        });
        getContentPane().add(refreshLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 80, 70));

        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });
        getContentPane().add(exitLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 80, 70));

        backgroundLbl.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        getContentPane().add(backgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrolledLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolledLblMouseClicked
        // TODO add your handling code here:
       new StudentList(adminInfo.get(0), adminInfo.get(1)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enrolledLblMouseClicked

    private void MaleLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleLblMouseClicked
        // TODO add your handling code here:
      new StudentList(adminInfo.get(0), adminInfo.get(1),"Male").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MaleLblMouseClicked

    private void femaleLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1),"Female").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_femaleLblMouseClicked

    private void csStudentsLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csStudentsLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1),"CS").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_csStudentsLblMouseClicked

    private void bioStudentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioStudentLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1),"Bio").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bioStudentLblMouseClicked

    private void bussinessStudentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bussinessStudentLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1),"Buiss").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bussinessStudentLblMouseClicked

    private void enrolledLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolledLblMouseEntered
        // TODO add your handling code here:
        enrolledLbl.setForeground(Color.red);
        ig.setImage("images/growth_hover.png", enrolledLbl);
        
    }//GEN-LAST:event_enrolledLblMouseEntered

    private void enrolledLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enrolledLblMouseExited
        // TODO add your handling code here:
        enrolledLbl.setForeground(Color.black);
         ig.setImage("images/growth.png", enrolledLbl);
    }//GEN-LAST:event_enrolledLblMouseExited

    private void MaleLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleLblMouseEntered
        // TODO add your handling code here:
        MaleLbl.setForeground(Color.red);
        ig.setImage("images/male_hover.png", MaleLbl);
    }//GEN-LAST:event_MaleLblMouseEntered

    private void MaleLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaleLblMouseExited
        // TODO add your handling code here:
         MaleLbl.setForeground(Color.black);
         ig.setImage("images/male.png", MaleLbl);
    }//GEN-LAST:event_MaleLblMouseExited

    private void femaleLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleLblMouseEntered
        // TODO add your handling code here:
        femaleLbl.setForeground(Color.red);
        ig.setImage("images/woman_hover.png", femaleLbl);
    }//GEN-LAST:event_femaleLblMouseEntered

    private void femaleLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleLblMouseExited
        // TODO add your handling code here:
         femaleLbl.setForeground(Color.black);
         ig.setImage("images/woman.png", femaleLbl);
    }//GEN-LAST:event_femaleLblMouseExited

    private void csStudentsLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csStudentsLblMouseEntered
        // TODO add your handling code here:
        csStudentsLbl.setForeground(Color.red);
        ig.setImage("images/cs_hover.png", csStudentsLbl);
    }//GEN-LAST:event_csStudentsLblMouseEntered

    private void csStudentsLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_csStudentsLblMouseExited
        // TODO add your handling code here:
        
        csStudentsLbl.setForeground(Color.black);
        ig.setImage("images/cs.png", csStudentsLbl);
    }//GEN-LAST:event_csStudentsLblMouseExited

    private void bioStudentLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioStudentLblMouseEntered
        // TODO add your handling code here:
        bioStudentLbl.setForeground(Color.red);
        ig.setImage("images/bio_hover.png", bioStudentLbl);
    }//GEN-LAST:event_bioStudentLblMouseEntered

    private void bioStudentLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bioStudentLblMouseExited
        // TODO add your handling code here:
        bioStudentLbl.setForeground(Color.black);
        ig.setImage("images/bio.png", bioStudentLbl);
    }//GEN-LAST:event_bioStudentLblMouseExited

    private void bussinessStudentLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bussinessStudentLblMouseEntered
        // TODO add your handling code here:
        bussinessStudentLbl.setForeground(Color.red);
         ig.setImage("images/buiss_hover.png", bussinessStudentLbl);
    }//GEN-LAST:event_bussinessStudentLblMouseEntered

    private void bussinessStudentLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bussinessStudentLblMouseExited
        // TODO add your handling code here:
        bussinessStudentLbl.setForeground(Color.black);
        ig.setImage("images/buiss.png", bussinessStudentLbl);
    }//GEN-LAST:event_bussinessStudentLblMouseExited

    private void archiveLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1),"Archive").setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_archiveLblMouseClicked

    private void archiveLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveLblMouseEntered
        // TODO add your handling code here:
        archiveLbl.setForeground(Color.red);
        ig.setImage("images/archives_hover.png", archiveLbl);
    }//GEN-LAST:event_archiveLblMouseEntered

    private void archiveLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveLblMouseExited
        // TODO add your handling code here:
        archiveLbl.setForeground(Color.black);
        ig.setImage("images/archives.png", archiveLbl);
    }//GEN-LAST:event_archiveLblMouseExited

    private void refreshLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseClicked
        // TODO add your handling code here:
        refreshStats();
    }//GEN-LAST:event_refreshLblMouseClicked

    private void refreshLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("images/refresh_hover.png", refreshLbl);
    }//GEN-LAST:event_refreshLblMouseEntered

    private void refreshLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseExited
        // TODO add your handling code here:
        ig.setImage("images/refresh.png", refreshLbl);
    }//GEN-LAST:event_refreshLblMouseExited

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
        // TODO add your handling code here:
        new WelcomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("images/logoutadminPage_hover.png", exitLbl);
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        // TODO add your handling code here:
        ig.setImage("images/logoutadminPage.png", exitLbl);
    }//GEN-LAST:event_exitLblMouseExited

    private void seeAllLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllLblMouseClicked
        // TODO add your handling code here:
        new StudentList(adminInfo.get(0), adminInfo.get(1)).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_seeAllLblMouseClicked

    private void seeAllLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("images/dashboard_hover.png", seeAllLbl);
        
    }//GEN-LAST:event_seeAllLblMouseEntered

    private void seeAllLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeAllLblMouseExited
        // TODO add your handling code here:
        ig.setImage("images/dashboard.png", seeAllLbl);
    }//GEN-LAST:event_seeAllLblMouseExited

    /**
     * @param args the command line arguments
     */
    private void loadAssets() {//Loads all Assets when the form is open
        adminNameLbl.setText(adminInfo.get(0));
        enrolledLbl.setText(enrolledLbl.getText() + " " + Integer.toString(db.enrolledNumber()));
        MaleLbl.setText(MaleLbl.getText() + " " + Integer.toString(db.maleEnrolled()));
        femaleLbl.setText(femaleLbl.getText() + " " + Integer.toString(db.femaleEnrolled()));

        String path = db.adminImg(adminInfo.get(0), adminInfo.get(1));
        ig.setImage(path, imgLogo);
        ig.setImage("images/adminHomePage4.jpg", backgroundLbl);
        ig.setImage("images/growth.png", enrolledLbl);
        ig.setImage("images/male.png", MaleLbl);
        ig.setImage("images/woman.png", femaleLbl);
        ig.setImage("images/cs.png", csStudentsLbl);
        ig.setImage("images/bio.png", bioStudentLbl);
        ig.setImage("images/buiss.png", bussinessStudentLbl);
        ig.setImage("images/dashbg2.png", statsBackgroundLBl);
        ig.setImage("images/archives.png", archiveLbl);
        ig.setImage("images/dashboardAdminLbl.png", dashboardLbl);
        ig.setImage("images/logoutadminPage.png", exitLbl);
        ig.setImage("images/dashboard.png", seeAllLbl);
        ig.setImage("images/refresh.png", refreshLbl);
        
        bioStudentLbl.setText(bioStudentLbl.getText() + " " + Integer.toString(db.BioEnrolled()));
        csStudentsLbl.setText(csStudentsLbl.getText() + " " + Integer.toString(db.csEnrolled()));
        bussinessStudentLbl.setText(bussinessStudentLbl.getText() + " " + Integer.toString(db.buissinessEnrolled()));
        archiveLbl.setText(archiveLbl.getText() + " " + Integer.toString(db.archivedStudents()));
    }
    private void refreshStats(){
        enrolledLbl.setText("");
        MaleLbl.setText("");
       femaleLbl.setText("");
        bioStudentLbl.setText("");
       csStudentsLbl.setText("");
        bussinessStudentLbl.setText("");
        
        enrolledLbl.setText(enrolledLbl.getText() + " " + Integer.toString(db.enrolledNumber()));
        MaleLbl.setText(MaleLbl.getText() + " " + Integer.toString(db.maleEnrolled()));
        femaleLbl.setText(femaleLbl.getText() + " " + Integer.toString(db.femaleEnrolled()));
        bioStudentLbl.setText(bioStudentLbl.getText() + " " + Integer.toString(db.BioEnrolled()));
       csStudentsLbl.setText(csStudentsLbl.getText() + " " + Integer.toString(db.csEnrolled()));
       bussinessStudentLbl.setText(bussinessStudentLbl.getText() + " " + Integer.toString(db.buissinessEnrolled()));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MaleLbl;
    private javax.swing.JLabel adminNameLbl;
    private javax.swing.JLabel archiveLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel bioStudentLbl;
    private javax.swing.JLabel bussinessStudentLbl;
    private javax.swing.JLabel csStudentsLbl;
    private javax.swing.JLabel dashboardLbl;
    private javax.swing.JLabel enrolledLbl;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel femaleLbl;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel refreshLbl;
    private javax.swing.JLabel seeAllLbl;
    private javax.swing.JLabel statsBackgroundLBl;
    // End of variables declaration//GEN-END:variables
}
