/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * This is the login form 
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    DataBase db = new DataBase();
    ImageIntializer ig = new ImageIntializer();

    public LoginPage() {
        initComponents();
        initAssests();
        this.setResizable(false);
        this.setTitle("Login");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginBtn = new javax.swing.JButton();
        userNametxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        passwrdLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        portalBtn = new javax.swing.JButton();
        loginPageLogo = new javax.swing.JLabel();
        contactLbl = new javax.swing.JLabel();
        footerLbl = new javax.swing.JLabel();
        gitHubLbl = new javax.swing.JLabel();
        faceBookLbl = new javax.swing.JLabel();
        instagramLbl = new javax.swing.JLabel();
        linkedInLbl = new javax.swing.JLabel();
        secondbackgroundLbl = new javax.swing.JLabel();
        BackGroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginBtn.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        loginBtn.setText("Log in");
        loginBtn.setBorder(null);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        loginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBtnKeyPressed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 30));

        userNametxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNametxtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userNametxtMouseReleased(evt);
            }
        });
        getContentPane().add(userNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 150, -1));

        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtKeyPressed(evt);
            }
        });
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 150, -1));

        passwrdLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(passwrdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 60, 50));

        userLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 50));

        portalBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        portalBtn.setText("Initial Page");
        portalBtn.setBorder(null);
        portalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(portalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 130, 50));
        getContentPane().add(loginPageLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 230, 150));

        contactLbl.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        contactLbl.setForeground(new java.awt.Color(255, 255, 255));
        contactLbl.setText("contact us?");
        getContentPane().add(contactLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 30));

        footerLbl.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        footerLbl.setForeground(new java.awt.Color(255, 255, 255));
        footerLbl.setText("All rights reserved ");
        getContentPane().add(footerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 260, 40));

        gitHubLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gitHubLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gitHubLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gitHubLblMouseExited(evt);
            }
        });
        getContentPane().add(gitHubLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 40, 40));

        faceBookLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faceBookLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                faceBookLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                faceBookLblMouseExited(evt);
            }
        });
        getContentPane().add(faceBookLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, 40));

        instagramLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instagramLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                instagramLblMouseExited(evt);
            }
        });
        getContentPane().add(instagramLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 40, 40));

        linkedInLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkedInLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkedInLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkedInLblMouseExited(evt);
            }
        });
        getContentPane().add(linkedInLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 40, 40));

        secondbackgroundLbl.setBackground(new java.awt.Color(0, 153, 153));
        secondbackgroundLbl.setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().add(secondbackgroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 390, 480));
        getContentPane().add(BackGroundLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        db.connectDB();
        if (db.login(userNametxt.getText(), passwordTxt.getText())) {
            new adminHomePage(userNametxt.getText(), passwordTxt.getText()).setVisible(true);
            this.setVisible(false);
        } else {
            userNametxt.setText("");
            passwordTxt.setText("");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void portalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portalBtnActionPerformed
        // TODO add your handling code here:
        new WelcomePage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_portalBtnActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void loginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBtnKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            db.connectDB();
            if (db.login(userNametxt.getText(), passwordTxt.getText())) {
                new adminHomePage(userNametxt.getText(), passwordTxt.getText()).setVisible(true);
                this.setVisible(false);
            } else {
                userNametxt.setText("");
                passwordTxt.setText("");
            }
        }
    }//GEN-LAST:event_loginBtnKeyPressed

    private void passwordTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            db.connectDB();
            if (db.login(userNametxt.getText(), passwordTxt.getText())) {
                new adminHomePage(userNametxt.getText(), passwordTxt.getText()).setVisible(true);
                this.setVisible(false);
            } else {
                userNametxt.setText("");
                passwordTxt.setText("");
            }
        }
    }//GEN-LAST:event_passwordTxtKeyPressed

    private void faceBookLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceBookLblMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/ibrahim.jber/"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }

    }//GEN-LAST:event_faceBookLblMouseClicked

    private void faceBookLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceBookLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("src/images/facebook_hover.png", faceBookLbl);
    }//GEN-LAST:event_faceBookLblMouseEntered

    private void faceBookLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceBookLblMouseExited
        // TODO add your handling code here:
        ig.setImage("src/images/facebook.png", faceBookLbl);
    }//GEN-LAST:event_faceBookLblMouseExited


    private void instagramLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramLblMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.instagram.com/ibrahim_jaber_ag/"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_instagramLblMouseClicked

    private void instagramLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("src/images/instagram_hover.png", instagramLbl);
    }//GEN-LAST:event_instagramLblMouseEntered

    private void instagramLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramLblMouseExited
        // TODO add your handling code here:
        ig.setImage("src/images/instagram.png", instagramLbl);
    }//GEN-LAST:event_instagramLblMouseExited


    private void linkedInLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInLblMouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.linkedin.com/in/ibrahim-jaber-82841a150/"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_linkedInLblMouseClicked

    private void linkedInLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("src/images/linkedin_hover.png", linkedInLbl);
    }//GEN-LAST:event_linkedInLblMouseEntered

    private void linkedInLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInLblMouseExited
        // TODO add your handling code here:
        ig.setImage("src/images/linkedin.png", linkedInLbl);
    }//GEN-LAST:event_linkedInLblMouseExited

    private void gitHubLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubLblMouseClicked
        // TODO add your handling code here:
                try {
            Desktop.getDesktop().browse(new URI("https://github.com/Ibrajber99"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_gitHubLblMouseClicked

    private void gitHubLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubLblMouseEntered
        // TODO add your handling code here:
        ig.setImage("src/images/github_hover.png", gitHubLbl);
    }//GEN-LAST:event_gitHubLblMouseEntered

    private void gitHubLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubLblMouseExited
        // TODO add your handling code here:
        ig.setImage("src/images/github.png", gitHubLbl);
    }//GEN-LAST:event_gitHubLblMouseExited

    private void userNametxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNametxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userNametxtMouseClicked

    private void userNametxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNametxtMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_userNametxtMouseReleased

    private void initAssests() {
        ig.setImage("src/images/encImage.png", BackGroundLbl);
        ig.setImage("src/images/loginPage.png", loginPageLogo);

        ig.setImage("src/images/IJSolutions.png", secondbackgroundLbl);
        ig.setImage("src/images/user.png", userLbl);
        ig.setImage("src/images/key.png", passwrdLbl);
        ig.setImage("src/images/logout.png", portalBtn);
        ig.setImage("src/images/login.png", loginBtn);

        ig.setImage("src/images/facebook.png", faceBookLbl);
        ig.setImage("src/images/instagram.png", instagramLbl);
         ig.setImage("src/images/linkedin.png", linkedInLbl);
         ig.setImage("src/images/github.png", gitHubLbl);
         

        footerLbl.setText(footerLbl.getText() + " " + "\u00a9");

        userNametxt.setBorder(BorderFactory.createLineBorder(BackGroundLbl.getBackground(), 2));
        passwordTxt.setBorder(BorderFactory.createLineBorder(BackGroundLbl.getBackground(), 2));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundLbl;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JLabel faceBookLbl;
    private javax.swing.JLabel footerLbl;
    private javax.swing.JLabel gitHubLbl;
    private javax.swing.JLabel instagramLbl;
    private javax.swing.JLabel linkedInLbl;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginPageLogo;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel passwrdLbl;
    private javax.swing.JButton portalBtn;
    private javax.swing.JLabel secondbackgroundLbl;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userNametxt;
    // End of variables declaration//GEN-END:variables
}
