/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.*;
import java.awt.Color;

/**
 *
 * Welcome page is first page the user gets greeted with 
 * very simple couple of intuitive buttons
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    ImageIntializer ig = new ImageIntializer();

    public WelcomePage() {
        initComponents();
        setAssests();
        this.setTitle("Portal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterPortalBtn = new javax.swing.JLabel();
        welcomeImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterPortalBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enterPortalBtn.setForeground(new java.awt.Color(255, 153, 102));
        enterPortalBtn.setText("Enter Portal");
        enterPortalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterPortalBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                enterPortalBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                enterPortalBtnMouseExited(evt);
            }
        });
        getContentPane().add(enterPortalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 150, 50));
        getContentPane().add(welcomeImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterPortalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPortalBtnMouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_enterPortalBtnMouseClicked

    private void enterPortalBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPortalBtnMouseEntered
        // TODO add your handling code here:
        enterPortalBtn.setForeground(Color.green);
        ig.setImage("images/portal_hover.png", enterPortalBtn);
        
    }//GEN-LAST:event_enterPortalBtnMouseEntered

    private void enterPortalBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterPortalBtnMouseExited
        // TODO add your handling code here:
        
        enterPortalBtn.setForeground(new java.awt.Color(255, 153, 102));
        ig.setImage("images/portal.png", enterPortalBtn);
    }//GEN-LAST:event_enterPortalBtnMouseExited

    private void setAssests() {
        ig.setImage("images/IJSolutions1.png", welcomeImg);
        ig.setImage("images/portal.png", enterPortalBtn);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterPortalBtn;
    private javax.swing.JLabel welcomeImg;
    // End of variables declaration//GEN-END:variables
}
